### ISSUE TITLE
Disabling authenticaion possible?

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-ui#177]
<a href="https://github.com/typhoon2099"><img src="https://avatars0.githubusercontent.com/u/828104?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [typhoon2099](https://github.com/typhoon2099)**
_Friday Apr 06, 2018 at 15:35 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-ui/issues/71_

----

It looks like Auth0 has removed the ability to get `user_metadata` and `app_metadata` from the `/userinfo` endpoint, which is breaking authentication for me. Is there a way I can disable authentication completely? I'm trying to deploy this project for a client so if it is indeed possible then I'll hide the app behind an nginx proxy and require authentication through that.

Side question: Which branches/tags should I be using for datatools-server and datatools-ui? I'm pretty confused as to which branches go together (mostly because I haven't been able to log into the system yet).

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Friday Apr 06, 2018 at 19:20 GMT_

----

The `DISABLE_AUTH` property in `env.yml` (for both datatools-ui and datatools-server) can be used to turn off authentication.

As for which branches to use, we recommend only using released versions rather than using some combination of branches, which are primarily used for active development and may be unstable.  We can better document which releases ought to be used in tandem, but the 2.x.x for both ui and server should be a safe combination.  These do use MapDB for persistence, so they will be different from the dev environment using Mongo and Postgres.

**Comment by landonreed** [comment]
<a href="https://github.com/typhoon2099"><img src="https://avatars0.githubusercontent.com/u/828104?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [typhoon2099](https://github.com/typhoon2099)**
_Monday Apr 09, 2018 at 09:02 GMT_

----

`DISABLE_AUTH` doesn't appear to do anything on the frontend, and I don't see anything in the frontend code which references it. I've tried clearing out the Auth0 related env variables but that just causes the frontend to error out (`Error: `ClientID` required as first parameter.`).

I'm using the `v2.0.4` release for the frontend and the `v2.0.1` release for the backend. I've also tried the `v4.0.0` frontend release as it was released the same day as the `v2.0.1` version of the backend, but the same issues arose. Can you please give me exact releases to use which work together? I still haven't found a matching pair (or at least not one that will allow me to disable the currently broken authentication).

**Comment by landonreed** [comment]
<a href="https://github.com/thomasrm"><img src="https://avatars2.githubusercontent.com/u/1469881?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [thomasrm](https://github.com/thomasrm)**
_Friday Aug 03, 2018 at 15:53 GMT_

----

Hi, 
I'd like to disable the authentication. I've set DISABLE_AUTH to false in both datatools-ui and datatools-server env.yml, but nothing changes in the frontend. 
Is there anything else to do?

**Comment by liegeandlief** [comment]
> [<img alt="" width="48" height="48" src="https://avatars0.githubusercontent.com/u/828104?v=4">](https://github.com/typhoon2099) **Comment by [typhoon2099](https://github.com/typhoon2099)**
> _Monday Apr 09, 2018 at 09:02 GMT_
> 
> `DISABLE_AUTH` doesn't appear to do anything on the frontend, and I don't see anything in the frontend code which references it. I've tried clearing out the Auth0 related env variables but that just causes the frontend to error out (`Error: `ClientID` required as first parameter.`).
> 
> I'm using the `v2.0.4` release for the frontend and the `v2.0.1` release for the backend. I've also tried the `v4.0.0` frontend release as it was released the same day as the `v2.0.1` version of the backend, but the same issues arose. Can you please give me exact releases to use which work together? I still haven't found a matching pair (or at least not one that will allow me to disable the currently broken authentication).

I am having the same issue as @landonreed. I have set `DISABLE_AUTH` to false in both the server and UI `env.yml` files. This works on the server but not in the UI. Doing a search of the UI code reveals that the only place `DISABLE_AUTH` is mentioned is in `deployment.md` where it says that setting it to true in the front end should disable authentication, but this does not seem to be the case.

Any help on this would be much appreciated :)
