### ISSUE TITLE
Publishing snapshot to version never completes

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-ui#224]
<a href="https://github.com/demory"><img src="https://avatars0.githubusercontent.com/u/653100?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [demory](https://github.com/demory)**
_Monday May 07, 2018 at 01:25 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-ui/issues/118_

----

Appears stuck here after 10-15 minutes. No errors in console.
![image](https://user-images.githubusercontent.com/653100/39680920-fc742c18-5173-11e8-9a16-e13eb004d15e.png)

**Comment by landonreed** [comment]
<a href="https://github.com/demory"><img src="https://avatars0.githubusercontent.com/u/653100?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [demory](https://github.com/demory)**
_Monday May 07, 2018 at 01:26 GMT_

----

Latest server messages:
![image](https://user-images.githubusercontent.com/653100/39680940-26dc7dac-5174-11e8-9dc4-5b937261de2d.png)

**Comment by landonreed** [comment]
<a href="https://github.com/demory"><img src="https://avatars0.githubusercontent.com/u/653100?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [demory](https://github.com/demory)**
_Monday May 07, 2018 at 15:14 GMT_

----

Appears this was a network connectivity problem in my test environment

**Comment by gelinger777** [comment]
![image](https://user-images.githubusercontent.com/184276/64927133-fdbdf980-d806-11e9-80ad-a2d37a807731.png)

I don't have even the snapshots tab 

+ The function Create Version From Snapshot does not work. I have latest dev ui and latest dev server
