### ISSUE TITLE
Refactor actions to make more concise code

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-ui#292]
<a href="https://github.com/evansiroky"><img src="https://avatars1.githubusercontent.com/u/3112493?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [evansiroky](https://github.com/evansiroky)**
_Thursday May 31, 2018 at 21:32 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-ui/issues/183_

----

Some common themes in this refactor will include:

* Using redux-actions.createAction instead of manually created actions
* Reducing the usage of actions that return functions and to instead use woonerf helpers whenever possible

- [ ] admin
- [ ] alerts
- [ ] common
- [ ] editor
- [ ] gtfs
- [ ] gtfsplus
- [ ] manager
- [ ] public
- [ ] signs

**Comment by evansiroky** [comment]
This has been completed.
