### ISSUE TITLE
Refactor containers

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-ui#355]
<a href="https://github.com/evansiroky"><img src="https://avatars1.githubusercontent.com/u/3112493?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [evansiroky](https://github.com/evansiroky)**
_Monday Sep 17, 2018 at 19:57 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-ui/issues/246_

----

Refactor the containers to have less verbosity.  This will mainly be accomplished by converting the `mapDispatchToProps` into an object with a list of all actions that can be used.  Also, a lot of mounting logic can also be moved into the constructor on the connected component which will also help in the process of updating to React 16.4+.  Flow typing will also be added as part of the refactor.

Refs #181

**Comment by evansiroky** [comment]
Already completed.
