### ISSUE TITLE
Merge dev to master

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-ui#360]
<a href="https://github.com/evansiroky"><img src="https://avatars1.githubusercontent.com/u/3112493?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [evansiroky](https://github.com/evansiroky)**
_Wednesday Oct 17, 2018 at 17:57 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-ui/pull/251_

----

It's time to bite the bullet and merge `dev` to `master`.

----

_**[evansiroky](https://github.com/evansiroky)** included the following code: https://github.com/catalogueglobal/datatools-ui/pull/251/commits_

**Comment by landonreed** [comment]
<a href="https://github.com/codecov-io"><img src="https://avatars0.githubusercontent.com/u/8655789?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [codecov-io](https://github.com/codecov-io)**
_Monday Oct 22, 2018 at 19:32 GMT_

----

# [Codecov](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`master@b4163e2`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `4.85%`.

[![Impacted file tree graph](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251/graphs/tree.svg?width=650&token=P6y8RDP2dF&height=150&src=pr)](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251?src=pr&el=tree)

```diff
@@           Coverage Diff            @@
##             master    #251   +/-   ##
========================================
  Coverage          ?   5.23%           
========================================
  Files             ?     324           
  Lines             ?   15405           
  Branches          ?    4649           
========================================
  Hits              ?     806           
  Misses            ?   12449           
  Partials          ?    2150
```


| [Impacted Files](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [lib/gtfs/reducers/validation.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251/diff?src=pr&el=tree#diff-bGliL2d0ZnMvcmVkdWNlcnMvdmFsaWRhdGlvbi5qcw==) | `20% <ø> (ø)` | |
| [lib/gtfs/components/gtfs-search.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251/diff?src=pr&el=tree#diff-bGliL2d0ZnMvY29tcG9uZW50cy9ndGZzLXNlYXJjaC5qcw==) | `0% <ø> (ø)` | |
| [lib/gtfsplus/selectors/index.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251/diff?src=pr&el=tree#diff-bGliL2d0ZnNwbHVzL3NlbGVjdG9ycy9pbmRleC5qcw==) | `0% <ø> (ø)` | |
| [lib/gtfsplus/components/GtfsPlusField.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251/diff?src=pr&el=tree#diff-bGliL2d0ZnNwbHVzL2NvbXBvbmVudHMvR3Rmc1BsdXNGaWVsZC5qcw==) | `0% <ø> (ø)` | |
| [lib/editor/containers/ActiveTripPatternList.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251/diff?src=pr&el=tree#diff-bGliL2VkaXRvci9jb250YWluZXJzL0FjdGl2ZVRyaXBQYXR0ZXJuTGlzdC5qcw==) | `0% <ø> (ø)` | |
| [lib/gtfs/containers/GlobalGtfsFilter.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251/diff?src=pr&el=tree#diff-bGliL2d0ZnMvY29udGFpbmVycy9HbG9iYWxHdGZzRmlsdGVyLmpz) | `0% <ø> (ø)` | |
| [lib/manager/components/FeedSourceSettings.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251/diff?src=pr&el=tree#diff-bGliL21hbmFnZXIvY29tcG9uZW50cy9GZWVkU291cmNlU2V0dGluZ3MuanM=) | `0% <ø> (ø)` | |
| [lib/editor/reducers/mapState.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251/diff?src=pr&el=tree#diff-bGliL2VkaXRvci9yZWR1Y2Vycy9tYXBTdGF0ZS5qcw==) | `40% <ø> (ø)` | |
| [lib/editor/components/HourMinuteInput.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251/diff?src=pr&el=tree#diff-bGliL2VkaXRvci9jb21wb25lbnRzL0hvdXJNaW51dGVJbnB1dC5qcw==) | `0% <ø> (ø)` | |
| [lib/editor/components/map/StopsLayer.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251/diff?src=pr&el=tree#diff-bGliL2VkaXRvci9jb21wb25lbnRzL21hcC9TdG9wc0xheWVyLmpz) | `0% <ø> (ø)` | |
| ... and [218 more](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251?src=pr&el=footer). Last update [b4163e2...79d8bbe](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/251?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by landonreed** [comment]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [landonreed](https://github.com/landonreed)**
_Monday Nov 05, 2018 at 15:32 GMT_

----

@evansiroky, I think for these release PRs we could probably follow the convention that appears to have emerged for other projects and just name it after the release version (which I think you can come up with by running semantic-release locally).  Could you update the PR with this info?

Also, I don't know if we have formally established this, but it might be a good idea to run the end-to-end test for a release and indicate with which version of the datatools-server repo it passed.

**Comment by evansiroky** [comment]
Done in #413
