### ISSUE TITLE
Refactor action type imports in components to reduce confusion

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-ui#374]
<a href="https://github.com/landonreed"><img src="https://avatars2.githubusercontent.com/u/2370911?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [landonreed](https://github.com/landonreed)**
_Wednesday Nov 28, 2018 at 15:52 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-ui/issues/265_

----

Mimic the changes in #259 so that actions that are imported for flow typing components have less chance of conflicting with destructured actions from `this.props`.

For example:
https://github.com/catalogueglobal/datatools-ui/blob/aae754e2593fa5ac066364de77ad9891596a258a/lib/common/components/Sidebar.js#L8-L10

**Comment by evansiroky** [comment]
Already completed.
