### ISSUE TITLE
Refactor flow typing in containers and use correct action types throughout application

### ISSUE THREAD

**Issue by landonreed** [conveyal/datatools-ui#380]
<a href="https://github.com/evansiroky"><img src="https://avatars1.githubusercontent.com/u/3112493?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [evansiroky](https://github.com/evansiroky)**
_Wednesday Dec 05, 2018 at 00:49 GMT_
_Originally opened as https://github.com/catalogueglobal/datatools-ui/pull/271_

----

Seeks to resolve #265, #246, #183.

----

_**[evansiroky](https://github.com/evansiroky)** included the following code: https://github.com/catalogueglobal/datatools-ui/pull/271/commits_

**Comment by landonreed** [comment]
<a href="https://github.com/codecov-io"><img src="https://avatars0.githubusercontent.com/u/8655789?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [codecov-io](https://github.com/codecov-io)**
_Wednesday Dec 05, 2018 at 06:42 GMT_

----

# [Codecov](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271?src=pr&el=h1) Report
> Merging [#271](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271?src=pr&el=desc) into [dev](https://codecov.io/gh/catalogueglobal/datatools-ui/commit/ead71f367e8bf0cbcfc96f31f8c8cdd0fae5ebf6?src=pr&el=desc) will **decrease** coverage by `<.01%`.
> The diff coverage is `0%`.

[![Impacted file tree graph](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/graphs/tree.svg?width=650&token=P6y8RDP2dF&height=150&src=pr)](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271?src=pr&el=tree)

```diff
@@           Coverage Diff            @@
##             dev    #271      +/-   ##
========================================
- Coverage   5.23%   5.22%   -0.01%     
========================================
  Files        324     324              
  Lines      15405   15431      +26     
  Branches    4649    4654       +5     
========================================
  Hits         806     806              
- Misses     12449   12472      +23     
- Partials    2150    2153       +3
```


| [Impacted Files](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [lib/gtfs/components/gtfsmapsearch.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2d0ZnMvY29tcG9uZW50cy9ndGZzbWFwc2VhcmNoLmpz) | `0% <ø> (ø)` | :arrow_up: |
| [lib/common/components/OptionButton.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2NvbW1vbi9jb21wb25lbnRzL09wdGlvbkJ1dHRvbi5qcw==) | `0% <ø> (ø)` | :arrow_up: |
| [lib/types/reducers.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL3R5cGVzL3JlZHVjZXJzLmpz) | `0% <ø> (ø)` | :arrow_up: |
| [lib/alerts/components/ModeSelector.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2FsZXJ0cy9jb21wb25lbnRzL01vZGVTZWxlY3Rvci5qcw==) | `0% <0%> (ø)` | :arrow_up: |
| [lib/alerts/components/AffectedServices.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2FsZXJ0cy9jb21wb25lbnRzL0FmZmVjdGVkU2VydmljZXMuanM=) | `0% <0%> (ø)` | :arrow_up: |
| [lib/common/containers/Login.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2NvbW1vbi9jb250YWluZXJzL0xvZ2luLmpz) | `0% <0%> (ø)` | :arrow_up: |
| [lib/alerts/components/AlertsViewer.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2FsZXJ0cy9jb21wb25lbnRzL0FsZXJ0c1ZpZXdlci5qcw==) | `0% <0%> (ø)` | :arrow_up: |
| [lib/alerts/components/AffectedEntity.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2FsZXJ0cy9jb21wb25lbnRzL0FmZmVjdGVkRW50aXR5Lmpz) | `0% <0%> (ø)` | :arrow_up: |
| [lib/alerts/containers/MainAlertsViewer.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2FsZXJ0cy9jb250YWluZXJzL01haW5BbGVydHNWaWV3ZXIuanM=) | `0% <0%> (ø)` | :arrow_up: |
| [lib/common/components/Sidebar.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2NvbW1vbi9jb21wb25lbnRzL1NpZGViYXIuanM=) | `0% <0%> (ø)` | :arrow_up: |
| ... and [35 more](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271?src=pr&el=footer). Last update [ead71f3...dbd9110](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by landonreed** [comment]
<a href="https://github.com/codecov-io"><img src="https://avatars0.githubusercontent.com/u/8655789?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [codecov-io](https://github.com/codecov-io)**
_Wednesday Dec 05, 2018 at 06:42 GMT_

----

# [Codecov](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271?src=pr&el=h1) Report
> Merging [#271](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271?src=pr&el=desc) into [dev](https://codecov.io/gh/catalogueglobal/datatools-ui/commit/ead71f367e8bf0cbcfc96f31f8c8cdd0fae5ebf6?src=pr&el=desc) will **decrease** coverage by `0.01%`.
> The diff coverage is `0.75%`.

[![Impacted file tree graph](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/graphs/tree.svg?width=650&token=P6y8RDP2dF&height=150&src=pr)](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271?src=pr&el=tree)

```diff
@@           Coverage Diff            @@
##             dev    #271      +/-   ##
========================================
- Coverage   5.23%   5.21%   -0.02%     
========================================
  Files        324     324              
  Lines      15405   15475      +70     
  Branches    4649    4655       +6     
========================================
+ Hits         806     807       +1     
- Misses     12449   12514      +65     
- Partials    2150    2154       +4
```


| [Impacted Files](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [lib/editor/components/HourMinuteInput.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2VkaXRvci9jb21wb25lbnRzL0hvdXJNaW51dGVJbnB1dC5qcw==) | `0% <ø> (ø)` | :arrow_up: |
| [lib/manager/util/index.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL21hbmFnZXIvdXRpbC9pbmRleC5qcw==) | `2.04% <ø> (ø)` | :arrow_up: |
| [lib/editor/components/ZoneSelect.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2VkaXRvci9jb21wb25lbnRzL1pvbmVTZWxlY3QuanM=) | `0% <ø> (ø)` | :arrow_up: |
| [lib/common/components/OptionButton.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2NvbW1vbi9jb21wb25lbnRzL09wdGlvbkJ1dHRvbi5qcw==) | `0% <ø> (ø)` | :arrow_up: |
| [lib/types/reducers.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL3R5cGVzL3JlZHVjZXJzLmpz) | `0% <ø> (ø)` | :arrow_up: |
| [lib/editor/components/timetable/EditableCell.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2VkaXRvci9jb21wb25lbnRzL3RpbWV0YWJsZS9FZGl0YWJsZUNlbGwuanM=) | `0% <ø> (ø)` | :arrow_up: |
| [lib/editor/components/timetable/Timetable.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2VkaXRvci9jb21wb25lbnRzL3RpbWV0YWJsZS9UaW1ldGFibGUuanM=) | `0% <ø> (ø)` | :arrow_up: |
| [lib/editor/components/EntityDetails.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2VkaXRvci9jb21wb25lbnRzL0VudGl0eURldGFpbHMuanM=) | `0% <ø> (ø)` | :arrow_up: |
| [lib/editor/components/EntityDetailsHeader.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2VkaXRvci9jb21wb25lbnRzL0VudGl0eURldGFpbHNIZWFkZXIuanM=) | `0% <ø> (ø)` | :arrow_up: |
| [lib/editor/components/pattern/EditSettings.js](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree#diff-bGliL2VkaXRvci9jb21wb25lbnRzL3BhdHRlcm4vRWRpdFNldHRpbmdzLmpz) | `0% <ø> (ø)` | :arrow_up: |
| ... and [89 more](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271?src=pr&el=footer). Last update [ead71f3...ae71d10](https://codecov.io/gh/catalogueglobal/datatools-ui/pull/271?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by evansiroky** [comment]
This was merged.
